name: publish
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build zip
        uses: papeloto/action-zip@v1
        with:
          files: .
          dest: edam-popovers.zip
