name: publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build zip
        uses: vimtor/action-zip@v1
        with:
          files: .
          dest: edam-popovers.zip
#      - uses: trmcnvn/chrome-addon@v2
#        with:
#          extension: amboeicaknkjjpffmdgkopjfljneolca
#          zip: edam-popovers.zip
#          client-id: ${{ secrets.CHROME_CLIENT_ID }}
#          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
#          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{edam-popovers@elixir.ut.ee}'
          xpi: edam-popovers.zip
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
